### ISSUE TITLE
use sinopia_profile_editor instead of github forked profile-edit

### ISSUE THREAD

**Issue by ndushay** [LD4P/sinopia_profile_editor#1]
- [x] master branch of sinopia_profile_editor should match lcnetdev/profile-edit with its commit history
- [x] issues from LD4P/profile-edit copied to sinopia_profile_editor
- [x] waffle board fixed up for new issues (in right columns / positions)
- [x] LD4P/profile-edit renamed LD4P/profile-edit-defunct
- [x] remove profile-edit-defunct from waffle board

**Comment by jgreben** [comment]
All done!
