### ISSUE TITLE
Verso spoof for Profile Editor GET calls

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_profile_editor#102]
Use LC's Profiles as a git submodule for Profile Editor, loading:
- [x]  profiles (see #108)
- [x] language (see #113)
- [ ]  ontologies - code in ontologies-spoof branch, waiting for #113 before PR
from ~~SSP git module~~ LC's verso as git submodule.

Consider using a different name than verso (already confusing enough)

Unit Tests for this:
1.  Loading of vocabularies produces JSON containing vocabularies (see #113)
1.  Loading of profiles produces JSON containing profiles (see #108)
1.  Loading of ontologies produces JSON containing ontologies
1.  Check size of arrays for each 

  

Blocks everything

**Comment by ndushay** [comment]
also make npm script to:  run grunt, get git submodule and then run tests without coverage

**Comment by atz** [comment]
Don't see any reason to tie (e.g.) `git submodule update` to a JS execution environment (via `npm` script).

**Comment by ndushay** [comment]
@atz we need files from the verso github repo (not ours) and we decided the simplest way to do this, and stay in sync with the upstream profile files was to use a git submodule.  we load specific files as part of profile server startup.

it's stupid but it's better than running their recto/verso back end stuff.

**Comment by ndushay** [comment]
@atz we needed a way to include the git submodule commands as part of a script, and the larger script needs npm.  Rather than do bash scripts or come up with another approach, I chose to use an npm script, as that is where our scripts live.  Moreover, it's done, it's merged.  If you have a constructive alternative, please submit a PR.

**Comment by jermnelson** [comment]
I have a PR #122 removing verso as git submodule. As @atz noted in the comments to issue #118 , the size of the resulting image with just the profiles and language RDF is 48 MB smaller than using the verso submodule approach and also fixes the problems we're seeing with circle-ci.
