### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by jgreben** [LD4P/sinopia_profile_editor#11]
To enable Sinopia to host an instance of in a cloud provider like AWS, a working Docker image and Docker compose environment is needed.

- [ ] Dockerfile, launches a working container.
~~  A `docker-compose.yml` file for creating a running sinopia profile editor using a `verso` json backend, required for the profile-editor ~~

**Comment by kirkhess** [comment]
See https://github.com/lcnetdev/verso/pull/10. I updated the ecosystem.config.js file to start everything.

**Comment by jermnelson** [comment]
Thanks Kirk, was looking at the latest changes in `verso` this morning and how the `ecosystem.config.js` is . I'm removing docker-compose check item for now
