### ISSUE TITLE
"Delete" action in Resource section is lining up with the wrong Property "bar"

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_profile_editor#110]
I know that Profile Editor isn't ready for user testing yet...but I noticed this when checking on something so I'm reporting it now.
I loaded the Monograph template.
When I open one of the Resource sections, the "Delete..." action is not lining up in the right place. See attached screenshot. "Delete Statement of Responsbility..." is not on the same line as "Statement of Responsibility"; it's in the "Edition Statement" line.

This happens in the existing LC Profile Editor also (http://bibframe.org/profile-edit/#/profile/4af68062-8c00-41cb-b311-fb6c450054f6) but only when you resize the screen to be narrower.

Our Profile Editor seems to have a narrower footprint to start with.
<img width="1060" alt="profileeditoralignment" src="https://user-images.githubusercontent.com/23069165/47521608-5b8cd000-d848-11e8-868f-b7e0de273fd8.png">

**Comment by astridu** [comment]
![subbar.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b6c7b5d3aa13600133488f8/125516c66e82c728ace21e0d46fb8198218391ebc3abaf51ab57f5973d047d317c06f27a25d2b529b91229560b5d4eac400b0d42f8fc8b2eb4aa2e32db025fb28c341521842f1bbeb98515be04be208e4883b4ba894dc1ef2f68.png)

**Comment by michelleif** [comment]
Possible solutions from discussion with Jeremy and Astrid: (1) remove the fixed width setting or (2) implement Astrid's design to shorten the Delete "button" to just "Delete" instead of "Delete [name of element]". Decided solution 2 is preferable.
