### ISSUE TITLE
Minimize use of waitFor in tests

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_profile_editor#137]
Minimize use of `waitFor` in  `beforeAll` and `afterEach` in jest tests as it slows down the entire testing suite.

In these tests so far:
 - [ ] `create-resource.test.js`
 - [ ] `new-profile.test.js` see this [comment](https://github.com/LD4P/sinopia_profile_editor/pull/136#discussion_r231624904)

**Comment by ndushay** [comment]
I think this was covered by the recent work to get rid of false positives and refactoring, PRs #213 #217
