### ISSUE TITLE
re-ordering of Resource Templates in a Profile does not get properly "saved"

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_profile_editor#139]
In the Profile Editor, the user can rearrange the order of Resource Templates by dragging and dropping. In Sinopia Profile Editor, when the user moves a Resource Template to a new position, the Profile is not properly "saved" (i.e., the exported Profile does not reflect the new order of Resource Templates and seems to replace the Resource Template that was moved with a copy of the adjacent Resource Template. The attached video explains this better.
Also attaching the 3 profile files from the video:
BIBFRAME 2.0 Note.json (the profile as exported from LC Profile Editor)
BIBFRAME 2.0 Note-2.json (the profile as opened in Sinopia Profile Editor, with Author field filled in)
BIBFRAME 2.0 Note-3.json (the profile as opened in Sinopia Profile Editor, with Author field filled in, and then the Resource Template "Script" moved to a new position. This is the profile that didn't properly "save")

**Comment by michelleif** [comment]
[Archive.zip](https://github.com/LD4P/sinopia_profile_editor/files/2567126/Archive.zip)

**Comment by jermnelson** [comment]
Opened issue [35](https://github.com/lcnetdev/profile-edit/issues/35) on LoC's Profile Edit as the bug was replicated on http://bibframe.org/profile-edit/. Will need to merge any fixes from the upstream repository.
