### ISSUE TITLE
Header fixes for Profile Editor

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_profile_editor#146]
Current header in the Profile Editor has non-functioning links. The following needs to be fixed:

- [ ] The `Linked Data Editor` menu item should link to https://sinopia.io
- [ ] The `Help and Resources` menu item should have the slide-out menu consistent with the Sinopia Editor, because we're not using React in the profile editor, may need to be Angular Component

**Comment by michelleif** [comment]
also the "Bibliographic Editor" menu item should be called "BFF (Bib Editor)" to be consistent with home page.
and if possible make the header look like the header on the homepage, with the Sinopia background design behind the header items (currently the header items are below the design element), and the Sinopia logo at top left clickable to return to home page.

**Comment by jermnelson** [comment]
My preference would be to  change the homepage to read **Bibliographic Editor** instead. BFF isn't really an acronym while **Bibliographic Editor** is clearer. Another option  could be **Linked Data Editor** for both the homepage and the Profile Editor.

**Comment by michelleif** [comment]
Let's call it "Linked Data Editor". @astridu could you make a complete list here in this ticket of changes that are needed to make the header consistent? For instance the Profile Editor has "Sinopia Profile Editor" all in the heading font, where the Editor has "Sinopia" in the header font and then "Editor Page" below. Which is the desired design?

**Comment by astridu** [comment]
1. Profile Editor page header: 
![image](https://user-images.githubusercontent.com/42216982/51143489-89f4c880-1803-11e9-838b-aca54ab8419e.png)

2. Linked Data Editor home with tabs:
![image](https://user-images.githubusercontent.com/42216982/51143564-b1e42c00-1803-11e9-80f5-285fe53f75ad.png)

3. Linked Data Editor home without tabs:
![image](https://user-images.githubusercontent.com/42216982/51143609-c32d3880-1803-11e9-8d0e-c860bffbd81c.png)

4. Sinopia landing page: 
![image](https://user-images.githubusercontent.com/42216982/51143626-cc1e0a00-1803-11e9-9d29-8334b2ab1517.png)
