### ISSUE TITLE
Remove nested resourceTemplates array from exported profiles

### ISSUE THREAD

**Issue by jgreben** [LD4P/sinopia_profile_editor#147]
If we use the Brief Export functionality insted of the Verbose export, it will remove empty arrays from the exported json.

**Comment by ndushay** [comment]
Note that our eventual intent is use use resourceTemplates array instead of valueTemplateRefs for propertyTemplates of type "resource".   But if we do, they won't be empty.  :-)

**Comment by ndushay** [comment]
I *think* this has been superseded by #178 -- don't output empty stuff.  @jgreben if you agree, please close this.

**Comment by jgreben** [comment]
@ndushay does this also need to also be about removing the ability to create nested resource templates (by removing the link/button/whatever)? Or is there/do we need another ticket for that?

**Comment by ndushay** [comment]
I already removed that button from the UI, so I think we're covered for that.

**Comment by michelleif** [comment]
can we close this?
