### ISSUE TITLE
Setup/Access URL for Profile Editor

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_profile_editor#15]
Determine / setup access URL (i.e. profile-editor.sinopia.org or some such)

Fixes #https://waffle.io/LD4P/sinopia/cards/5ba538b612a4b20030699a89

**Comment by ndushay** [comment]
we want:

- url for profile editor    sinopia.org/profile_editor
- url for bibframe editor   sinopia.org/bff ?
- possibly url that goes to page allowing either ?

**Comment by ndushay** [comment]
![mingus.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5522c457e2d8b81e00d2eea6/125516c66e82c728ace21e0d46e59d94249790ebc3abaf51ab57f5973d047d317c06f27a25d2b529b91229560b5d4eac400b0d42f8fc8b2eb4aa2e32db025fb28c341521842f1bbeb98515be04b9288b4784b1b98e49c4e12f68.png)

**Comment by michelleif** [comment]
ask Julian about possibilities: getting new domain like sinopia.org? using ld4p.org/...?

**Comment by michelleif** [comment]
per vivian: I asked Julian about how to register a domain name under Amazon. He said “We can register domains through Amazon, which we’ve done for some other projects….. We can register any domain name we want that is available. Whether or not the site should have Stanford branding depends on the project. the iiif.io site (another one of ours) for example doesn’t have our branding.” So Michelle and Astrid, you can just think of the url and assign to Rob to make that happen. Michelle, you might want to ask Phil or Tom or ? before we finalize the url.

**Comment by cmh2166** [comment]
Yeah, we have plenty of examples of how to do this within AWS (see taco, dlme, rialto, histonets [cidr], etc. - can provide links to terraform if helpful). Just need a name.
