### ISSUE TITLE
Add Performed Music Ontology for look-ups

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_profile_editor#172]
Add http://performedmusicontology.org/ OWL file

**Comment by michelleif** [comment]
@jermnelson adding PMO as a QA authority? or as an additional value in Select Resource / Select Property menu?

**Comment by michelleif** [comment]
@jermnelson is this still relevant?

**Comment by jermnelson** [comment]
> @jermnelson is this still relevant?

I think @NancyL needs to weigh in on this issue. I think inclusion is for the `Select Resource/Select Property` menus and not as QA source.

**Comment by michelleif** [comment]
will assume covered by #182 . if not please reopen
