### ISSUE TITLE
use css linter (requires #6)

### ISSUE THREAD

**Issue by ndushay** [LD4P/sinopia_profile_editor#18]
Are we concerned with any non-js code in the repo?

Is it no b/c PHP code is for storing the profiles, which we aren't?

What about css linting or whatever?

**Comment by jgreben** [comment]
I think CSS linting would be valid. We are not going to use the PHP code AFAIK, and in fact that code was removed in our latest rebase from lcdevnet upstream.

**Comment by jgreben** [comment]
Lots of choices:
https://www.npmjs.com/package/csslint
https://www.npmjs.com/package/csslint-stylish
https://www.npmjs.com/package/csslint-cli
https://www.npmjs.com/package/css-lint
https://www.npmjs.com/package/stylelint

**Comment by ndushay** [comment]
we're ignoring this for now;  will seek it out to re-open if we decide to do css linting on profile editor.

**Comment by michelleif** [comment]
@jermnelson can we close this

**Comment by jermnelson** [comment]
Closing; I don't think we want to add css linting in this code base.
