### ISSUE TITLE
Branding for Sinopia Profile Editor

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_profile_editor#2]
We need consistent branding for the Sinopia Profile Editor.

**Comment by jgreben** [comment]
@astridu I think the Create a new profile page should not include any default entities (e.g. Bibframe Work, Instance). It should look something like: https://ld4p-loc-profiles-dev.stanford.edu/#/profile/create (i.e only the Profile section, no default entities)

**Comment by jgreben** [comment]
Creating a brand new profile:
<img width="1017" alt="screen shot 2018-09-28 at 10 30 05 am" src="https://user-images.githubusercontent.com/3093850/46224080-1be6cd00-c30a-11e8-9c23-afeac4c6de25.png">

**Comment by astridu** [comment]
Got it. thank you! Should the Profile section be expanded when you come to this screen? Seems strange that it's closed. 
![image](https://user-images.githubusercontent.com/42216982/46224834-45085d00-c30c-11e8-9060-dac9664ce2be.png)

**Comment by astridu** [comment]
Also, do you have bandwidth to rebrand the elements you are re-using (like the tables/forms/buttons)? I can mock it up in the Sinopia branding, or leave it as is. Just let me know.

**Comment by jgreben** [comment]
Having it expanded by default would be a good idea. Otherwise it looks too empty and, yes strange. Also I think the rebranding that you are suggesting will just be some css overrides, so that will not be too much work. The existing project uses font-awesome and bootstrap, so making changes especially within those frameworks would be easy.

**Comment by michelleif** [comment]
Footer:
Sinopia is a project of [Linked Data for Production 2 (LD4P2)](http:www.ld4p.org), funded by the Andrew W. Mellon Foundation.

**Comment by astridu** [comment]
Will you ask Tom about the copyright, or did you want me to do that? Also, did you want to list the partner institutions participating? (just a suggestion, I noticed it on the Samvera site).
thanks!

**Comment by jgreben** [comment]
@astridu Are you able to provide the following, as needed for the proposed designs?

- [ ] Font-family for entire project
- [ ] Fonts for specified elements
- [ ] HTML Colors for specified elements
- [ ] Footer image
- [ ] Header/footer/background colors
- [ ] Text and Link colors
- [ ] Table or div colors

**Comment by astridu** [comment]
Font: Source Sans Pro, black (or white if on dark background)
colors
Button = dark teal 00505C
Table header bgcolor = dark sandstone 8C8A83
Table bgcolor = light sandstone F8F6EF
horizontal rule in profile editor header = dark brown 2F2424
If you create an Invision account, you can see the css if you click on the Inspect button (</>) at the bottom of the prototype. https://invis.io/5YNLDND63KF#/322451431_Profile_Editor_Page_1

**Comment by astridu** [comment]
View Prototype: https://invis.io/5YNLDND63KF#/322451430_Profile_Editor_Page_2

**Comment by jgreben** [comment]
Fixed by #85

**Comment by michelleif** [comment]
Please change the colors that are used once you are editing a profile, the blue text on gold background is really hard to read for the names of the elements within the Profile, and you can barely see the little triangle at left to open those pieces, and the white text on gold background also hard to read for the Delete/Change actions at right. I know I said we want a different color scheme to differentiate the Profile Editor from the Editor, but I think it's enough that the header and the names of the profiles are in a different color scheme. The original is a lot easier to read. Attaching screenshots of both for comparison.

**Comment by astridu** [comment]
In response to @michelleif comment above:

https://invis.io/5YNLDND63KF#/326508536_Profile_Editor_Page_2a
MVP changes
1. Change background color of subheaders to: E5C9A3

Not sure if any of these are in scope, so I've labeled these "Nice to have changes"
1. Change 'template' to 'section' (feedback from DC meeting) and add explanatory text at the top of the page.
2. I defined a style for text that has a tooltip to be the link color plus a dotted line underneath
3. Use blue carat for expand/contract
4. Shorten to [trash icon] Delete and just put the [move icon] on the far right to indicate the section is moveable.
5. Whenever there is an '+ Add Something', it should use the same dotted line button style as the one at the bottom of the page.
6. The tooltips coming in when you hover over the data entry field is really annoying. Could we instead move the hover to the field label?
7. I'm confused by the Add/Delete button at the bottom.
8. Can you add a few more spaces between the 2 links at the top of the page (Bib Editor and Help and Resources)?

**Comment by michelleif** [comment]
If the text is going to be blue then it's really hard to read with E5C9A3 as background. Can we just do light gray like LC or a lighter gold?

Given all the work we have to do, the other changes are out of scope; we can put them in another ticket and keep it in the backlog in case we have time later.

**Comment by astridu** [comment]
Here are 2 options, both accessible (AA) - light gold and light gray. LMK which you prefer.

lighter ochre #F2E9D9
![image](https://user-images.githubusercontent.com/42216982/47229553-d2bff100-d37c-11e8-96c6-e02672e1869d.png)

Lighter gray
![image](https://user-images.githubusercontent.com/42216982/47229593-e9fede80-d37c-11e8-91b5-6635b2ba9ef2.png)

**Comment by astridu** [comment]
![image](https://user-images.githubusercontent.com/42216982/47229631-0c90f780-d37d-11e8-8862-f8f31414f67f.png)

**Comment by michelleif** [comment]
lighter gray is better. I'm tagging this as a bug so we know that it needs to get fixed. It is unreadable as is. thanks!

**Comment by astridu** [comment]
Lighter gray is DFDFDF
