### ISSUE TITLE
Resource Template Dates optional or required?

### ISSUE THREAD

**Issue by kirkhess** [LD4P/sinopia_profile_editor#207]
If you create a new resource template there’s no date property on a resource template, but all the spoofed ones have them. In the schemas, 0.0.9 does not require dates on resource templates but in 0.1.0 it is required.  How will that date will be populated? I'm asking so I populate the dates the same way in the LC profiles from https://github.com/lcnetdev/profile-edit

Schema:
https://ld4p.github.io/sinopia/schemas/0.0.9/resource-template.json

```
  "required": [
    "id",
    "propertyTemplates",
    "resourceLabel",
    "resourceURI",
    "schema"
  ],
```
vs. 
https://ld4p.github.io/sinopia/schemas/0.1.0/resource-template.json
```
  "required": [
    "author",
    **"date",**
    "id",
    "propertyTemplates",
    "resourceLabel",
    "resourceURI",
    "schema"
  ]
```

This comes into play with imported profiles. The Harvard Item profile  was a copy of the sinopia copy of our Item profile. 
https://github.com/LD4P/sinopia_sample_profiles/blob/master/cohort-profiles/Harvard/Harvard%20Library%20BIBFRAME%202.0%20Item.json

If you look at the rt date, it didn’t change and there's no way to change it in the interface.. It was valid though because it already had a date from the spoofed content (plus it uses the 0.0.9 schema).

```
      "resourceURI":"http://id.loc.gov/ontologies/bibframe/Item",
      "resourceLabel":"BIBFRAME 2.0 Item",
      "id":"Harvard:resourceTemplate:bf2:Item",
      "date":"2017-08-08",
      "author":"NDMSO",
      "schema":https://ld4p.github.io/sinopia/schemas/0.0.9/resource-template.json
```

vs. the profile (where he changed the date)
```
      "id":"Harvard:profile:bf2:Item",
      "title":"Harvard Library BIBFRAME 2.0 Item",
      "description":"Harvard Item for all formats (testing)",
      "date":"2019-03-26",
      "author":"Marc McGee",
      "schema":"https://ld4p.github.io/sinopia/schemas/0.0.9/profile.json"
```

**Comment by michelleif** [comment]
Resource Template dates are optional for now. We are not using 0.1.0 because it was too strict for various reasons. Can we close this ticket @kirkhess

**Comment by kirkhess** [comment]
Closing ticket.
