### ISSUE TITLE
Help & Resources link on Profile Editor page needs to bring up same sidebar as Help & Resources on homepage and Editor page

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_profile_editor#208]
the "Help & Resources" tab on the Profile Editor is not pointing to the latest Help & Resources content. If you compare the sidebar that comes up from sinopia.io or sinopia.io/editor to the one that comes up from profile-editor.sinopia.io you'll see the difference. 

sinopia.io and sinopia.io/editor Help & Resources link are bringing up the correct sidebar. can we just use the same sidebar on Profile Editor Help & Resources?

**Comment by michelleif** [comment]
this is not working on DEV

**Comment by ndushay** [comment]
I wonder if this is another profile editor thing waiting for a successful build in circleci so we can create a docker image so we can deploy to dev ...

(I am working on fixing the broken build #211)

**Comment by jermnelson** [comment]
I believe @ndushay is right; this should be addressed once the broken build is fixed in #211

**Comment by ndushay** [comment]
@michelleif I believe this is fixed now

**Comment by michelleif** [comment]
looks good in all 3 environments. thank you!!!!
