### ISSUE TITLE
DEV Profile Editor header links need to point to DEV not PRD

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_profile_editor#210]
https://profile-editor.development.sinopia.io/#/profile/sinopia, the Sinopia link at upper left points to https://sinopia.io/ instead of to development, and the Linked Data Editor link points to https://sinopia.io/editor instead of to development

**Comment by ndushay** [comment]
contrary to popular belief, this was NOT fixed and waiting for a new docker image

**Comment by ndushay** [comment]
@michelleif I believe this is fixed now;  I need to deploy to stage to test it there (and prod, of course)

**Comment by ndushay** [comment]
@michelleif  I was able to confirm this is fixed in dev, stage and prod.  If you disagree please re-open ticket or open a new one.

https://profile-editor.development.sinopia.io
https://profile-editor.stage.sinopia.io
https://profile-editor.sinopia.io
