### ISSUE TITLE
in profile editor, make "Templates" (in Property Template definition, for type = resource) be a free-text field instead of a dropdown list

### ISSUE THREAD

**Issue by ndushay** [LD4P/sinopia_profile_editor#212]
When creating a profile with the profile editor, 
When editing a property within a resource template,
If selecting a (resource) template id for a property of type "resource" via the selector (confusingly, named "Templates"), then these ids should be resource template ids, NOT profile ids, from sinopia server.

This image should help -- the ids in the selector need to be resource template ids from sinopia server.  

![image](https://user-images.githubusercontent.com/96775/57709358-b7217e00-761f-11e9-9d63-a003de64bf99.png)

@jgreben maybe these ARE the spoofed resource ids, as they were named "profile" ... but are they from the server?

@michelleif please confirm

**Comment by kirkhess** [comment]
FYI that is a list of resource templates, from the old spoofed list.

Here's the current interface:
![image](https://user-images.githubusercontent.com/1419922/57712846-52761b80-763f-11e9-8135-2935d44c64e9.png)

I renamed all the resource templates so they start with lc:RT. Profiles start with lc:profile:bf2
http://bibframe.org/verso/api/configs?filter[where][configType]=profile

**Comment by michelleif** [comment]
yes these are supposed to be resource template IDs, ideally directly from Sinopia server, but didn't we say that since the Profile Editor doesn't yet interact directly with the Sinopia Server, we just get the list some other way, and if there are new RTs to be added to the list, users will have to email sinopia_admin to get them added.

**Comment by michelleif** [comment]
@ndushay can we close this?

**Comment by michelleif** [comment]
based on discussion 5/20 we decided to make this a free text field and leave it to the profile creator to enter the ID of the resource template they want to refer to, since at this time it is too much work to do the ideal of asking trellis for a list of known resource templates

**Comment by michelleif** [comment]
this will also fix https://github.com/LD4P/sinopia/issues/162

**Comment by michelleif** [comment]
ignore above erroneous reference to/form 162

**Comment by ndushay** [comment]
@michelleif  the existing popover text is "A resource template identifier that defines the expected value." ... which seems kinda ... circular?

Would you like to suggest something better?  

"A resource template identifier this property uses to nest information" 
"A resource template identifier"
"An identifier for the resourceTemplate that will shape the information for this property"
...

**Comment by michelleif** [comment]
Yes good idea let's change it. For the part in the blue bar "Value Template Reference" I don't know if you can change that, but if you can, please change that to "ID of Resource Template to embed"

And then change the text below to "For use with type = resource. Enter the ID of the Resource Template that will be the object of this property."

**Comment by ndushay** [comment]
@michelleif this should be on development if you want to take a look.

**Comment by michelleif** [comment]
looks great thank you!!!!
