### ISSUE TITLE
tag version (docker image) for sinopia_profile_editor

### ISSUE THREAD

**Issue by ndushay** [LD4P/sinopia_profile_editor#214]
- [x] Bump version
- [x] Publish updated npm package
- [x] Create and push git tag
- [x] Create new GitHub release
- [x] Build and push tagged image
- [x] Update documentation to reflect above steps

**Comment by mjgiarlo** [comment]
This is now complete:

* https://github.com/LD4P/sinopia_profile_editor/releases/tag/v0.1.1
* https://github.com/LD4P/sinopia_profile_editor/tree/v0.1.1
* https://www.npmjs.com/package/sinopia_profile_editor
* https://hub.docker.com/r/ld4p/sinopia_profile_editor/tags
