### ISSUE TITLE
for Values/URI dropdown, add option to search for Sinopia descriptions

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_profile_editor#227]
once catalogers start describing things in Sinopia, we will need a way to set up Profiles with a lookup that lets the cataloger search for things already cataloged in Sinopia, and refer to them

we will need another entry in the Values/URI dropdown, corresponding to a "Sinopia datastore" config in https://github.com/LD4P/sinopia_editor/blob/master/static/spoofedFilesFromServer/fromSinopiaServer/lookupConfig.json

unclear whether profile creators will want to be as specific as "Sinopia Works" vs "Sinopia Instances" or it's just "all Sinopia URIs"

**Comment by justinlittman** [comment]
I think this is completed by https://github.com/LD4P/sinopia_profile_editor/commit/22479fa891819384d047a2231219105c7c3ea3a4

![2019-08-01_1536](https://user-images.githubusercontent.com/588335/62322036-2023cf80-b472-11e9-9d93-8906e9a8c70b.png)


@michelleif If you disagree, feel free to re-open the ticket.
