### ISSUE TITLE
"Select Resource" modal has no data in Firefox Extended Support Release browser

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_profile_editor#229]
From an email from Rachelle Nelson:
Hello,

 

At yesterday’s Profiles Working Group meeting, a few of us reported a problem with using “Select Resource” in the Profile Editor. I followed the instructions for clearing my browser’s (Firefox) local storage but the problem persists. When creating a new profile and after clicking on Add Resource Template and entering an ID, I click on “Select Resource.” A box appears with “Choose Vocab Template” as the header with no options to select anything. The “Create a Sinopia Profile from Scratch” document indicates a “Choose Resource Template” box should open with the option to select an ontology and resource class type.

 Hello,

 

At yesterday’s Profiles Working Group meeting, a few of us reported a problem with using “Select Resource” in the Profile Editor. I followed the instructions for clearing my browser’s (Firefox) local storage but the problem persists. When creating a new profile and after clicking on Add Resource Template and entering an ID, I click on “Select Resource.” A box appears with “Choose Vocab Template” as the header with no options to select anything. The “Create a Sinopia Profile from Scratch” document indicates a “Choose Resource Template” box should open with the option to select an ontology and resource class type.

 

Instead, this is what I get:

![image001](https://user-images.githubusercontent.com/71847/59714106-19950d80-91ce-11e9-8e96-e5ffa14d6912.png)

**Comment by ndushay** [comment]
This data used to come from versoSpoof.  See also #764

**Comment by aaron-collier** [comment]
@jermnelson when I run this locally, I'm getting data in the form. Is this still an open issue?

**Comment by jermnelson** [comment]
Thanks for checking this. Looks the Select Resource is populating correctly in development and production. I'll close this issue and write a follow-up email to Rachelle Nelson.

**Comment by michelleif** [comment]
pinpointed this to Firefox Extended Support Release. works fine on regular Firefox. leaving this open so we'll know it's an issue, but very low priority since works fine in other browsers

**Comment by michelleif** [comment]
since there are multiple other browsers people can use, i'm moving this out of work cycle 1. also, this is documented in Known Issues.
