### ISSUE TITLE
test for rendering UI with angular, etc.

### ISSUE THREAD

**Issue by ndushay** [LD4P/sinopia_profile_editor#23]
on laptops and circleci

- test angular rendering of profile editor

-------
- test that loading profile is possible (#24) --> possibly postponed until we are loading profiles our way (or possibly initial test that shows a profile is loaded somehow)
- test that saving profile is possible -- ditto (as part of #4 ?)

**Comment by jgreben** [comment]
"saving" a profile means downloading the profile JSON.
