### ISSUE TITLE
Update lookupConfig.json

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_profile_editor#234]
Update https://github.com/LD4P/sinopia_profile_editor/blob/master/sample_data_from_verso/data/config/lookupConfig.json with the latest version from [Sinopia Editor](https://github.com/LD4P/sinopia_profile_editor/)

**Comment by michelleif** [comment]
@aaron-collier is this the work that is going to allow us in the Profile Editor to specify that a lookup goes to look up Sinopia resources?

**Comment by michelleif** [comment]
@aaron-collier nvm I think that's #227
