### ISSUE TITLE
add trash can delete for Value Data Type

### ISSUE THREAD

**Issue by RobertRohr** [LD4P/sinopia_profile_editor#242]
When you delete a URI from the Value Data Type field in the Profile editor, the field does not go away. When you look at the JSON, the field data is still there with an empty value. This causes an error message when you try to load the template into the Linked Data editor.
<img width="703" alt="JSON" src="https://user-images.githubusercontent.com/48070028/63466466-2b866d00-c418-11e9-9af1-a6c5aca49116.png">

**Comment by michelleif** [comment]
there's no trash can for valueDataType

**Comment by justinlittman** [comment]
@michelleif Can you provide specific steps to reproduce this?

**Comment by michelleif** [comment]
SIDE NOTE (will deal with this separately): if you use the Profile Editor's "Select Datatype" option and choose a value from one of the vocabularies in the menu, the Profile Editor fills in not only dataTypeURI but also dataTypeLabel and remark, which our schema does not like!!!
```    "valueDataType": {
                "dataTypeURI": "http://www.w3.org/1999/02/22-rdf-syntax-ns#Property",
                "dataTypeLabel": "Property",
                "remark": "The class of RDF properties."
              }```

error message upon importing:
```{ keyword: 'additionalProperties', dataPath: '.Profile.resourceTemplates[0].propertyTemplates[1].valueConstraint.valueDataType', schemaPath: '#/properties/valueConstraint/properties/valueDataType/additionalProperties', params: { additionalProperty: 'dataTypeLabel' }, message: 'should NOT have additional properties', schema: false, parentSchema: { type: 'object', title: 'Value Data Types', description: 'Data Type information: Type URI.', additionalProperties: false, properties: [Object] }, data: { dataTypeURI: 'http://www.w3.org/1999/02/22-rdf-syntax-ns#Property', dataTypeLabel: 'Property', remark: 'The class of RDF properties.' } }, { keyword: 'additionalProperties', dataPath: '.Profile.resourceTemplates[0].propertyTemplates[1].valueConstraint.valueDataType', schemaPath: '#/properties/valueConstraint/properties/valueDataType/additionalProperties', params: { additionalProperty: 'remark' }, message: 'should NOT have additional properties', schema: false, parentSchema: { type: 'object', title: 'Value Data Types', description: 'Data Type information: Type URI.', additionalProperties: false, properties: [Object] }, data: { dataTypeURI: 'http://www.w3.org/1999/02/22-rdf-syntax-ns#Property', dataTypeLabel: 'Property', remark: 'The class of RDF properties.' } }```

**Comment by michelleif** [comment]
here is a sample profile containing one resource template with two fields that both have valuedatatype URIs (even though we aren't using this setting to do anything, some people still fill it out, or have brought profiles over from LC, who sometimes uses it)
[test_delete_valuedatatype.json.txt](https://github.com/LD4P/sinopia_profile_editor/files/3802023/test_delete_valuedatatype.json.txt)

uploads ok

now:
-open that same profile in the Profile Editor (not a text editor)
-decide you don't want the valuedatatypeURI in the second field (`http://www.w3.org/1999/02/22-rdf-syntax-ns#Property`)
-the only way to delete is to highlight and remove the text (there's no trash can)
-highlight and remove the text
-save

look at it in Atom or other text editor

you're left with:
```"valueDataType": {
                "dataTypeURI": ""```

now try to import into Sinopia
```The profile you provided was not in an acceptable format: Error: [ { keyword: 'format', dataPath: '.Profile.resourceTemplates[0].propertyTemplates[1].valueConstraint.valueDataType.dataTypeURI', schemaPath: '#/properties/valueConstraint/properties/valueDataType/properties/dataTypeURI/format', params: { format: 'uri' }, message: 'should match format "uri"', schema: 'uri', parentSchema: { type: 'string', format: 'uri', title: 'Data Type URI', description: 'URI for the Data Type of the Lookup Value default.', example: [Object] }, data: '' } ]```

it doesn't like the blank URI

SOLUTION:
fix Profile Editor to add trash can which will delete the value properly
OR
fix Sinopia (fix schema?) to ignore blank valuedatatypeURI
