### ISSUE TITLE
Add support for subtype = "context" for propertyTemplate

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_profile_editor#245]
Adds user interface to indicate a subtype = "context" to support display of extended context in the Editor. Note: The resource template must validate as [0.2.1](https://github.com/LD4P/sinopia/tree/master/schemas/0.2.1) schema.

**Comment by michelleif** [comment]
requires ld4p/sinopia#252

**Comment by michelleif** [comment]
and we need to document somewhere (is it already?) which lookups have context available, and how to use this feature

**Comment by michelleif** [comment]
don't need this since we did https://github.com/LD4P/sinopia_editor/issues/1338
