### ISSUE TITLE
Design profile editor

### ISSUE THREAD

**Issue by ndushay** [LD4P/sinopia_profile_editor#26]
result:

screens from vanilla current profile-editor, and then replacement screens showing what OUR sinopia profile-editor should look like,

*If* there is a screen from which will base OUR screen, the relationship / changes are important to indicate

**Comment by astridu** [comment]
Design documentation for Profile editor. @michelleif do you want to review before the devs pick this up? https://docs.google.com/document/d/1OjJuk8FAIRFvrxIOoNR7hcCOem_rsAt6qyn7t5Y5wFg/edit?usp=sharing

**Comment by jgreben** [comment]
Fixed by #85
