### ISSUE TITLE
update add value dropdown in Profile Editor

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_profile_editor#280]
for Discogs lookups, the only choice in current Profile Editor dropdown is "Discogs" but in the authority config https://github.com/LD4P/sinopia_editor/blob/master/static/authorityConfig.json there's also `Discogs Releases` and `Discogs Masters` which should be choices too

**Comment by justinlittman** [comment]
This requires copying over the authorityConfig from BFF to PE and redeploying the PE. I believe in PE it is still called lookupConfig. It is OK to replace the entire file.
