### ISSUE TITLE
linter runs cleanly

### ISSUE THREAD

**Issue by ndushay** [LD4P/sinopia_profile_editor#31]
- is there a way to generate a TODO list so it can ignore existing problems, e.g. in static folder (so we don't diverge from upstream)
- is there an autocorrect we can use for the files of interest (e.g. bfe)

**Comment by jgreben** [comment]
See: https://eslint.org/docs/2.0.0/rules/no-warning-comments

**Comment by jgreben** [comment]
eslint has a `--fix` flag that you can run from the command line.
