### ISSUE TITLE
CI runs linter

### ISSUE THREAD

**Issue by ndushay** [LD4P/sinopia_profile_editor#32]
We want CI to:

- run eslint. <-- fail for problems
- do build. <-- fail for problems (is there a react or other build that needs to happen?)
- have tests that do something. <-- fail for problems
    - with code coverage. <-- fail for reducing coverage (see #19)

depends on #31

**Comment by jgreben** [comment]
I think this is done now. Please confirm.

**Comment by ndushay** [comment]
I agree;  I connected it to PR #42 so it will close when that is merged.
