### ISSUE TITLE
Use Sinopia branding for header and footer

### ISSUE THREAD

**Issue by jgreben** [LD4P/sinopia_profile_editor#37]
Also remove the breadcrumbs.

Before:
<img width="1207" alt="screen shot 2018-10-01 at 11 18 30 am copy" src="https://user-images.githubusercontent.com/3093850/46307882-04f3e500-c56d-11e8-8dec-96ae819c63b6.png">

After:

<img width="1025" alt="screen shot 2018-10-01 at 11 31 19 am" src="https://user-images.githubusercontent.com/3093850/46308142-bdba2400-c56d-11e8-8272-19f183dc4763.png">

**Comment by jgreben** [comment]
Need branded footer...

**Comment by michelleif** [comment]
see #2 for specs

**Comment by jgreben** [comment]
Fixed by #85
