### ISSUE TITLE
"Create Profile" page changes

### ISSUE THREAD

**Issue by jgreben** [LD4P/sinopia_profile_editor#39]
- [x] "Profile" > "Create a new profile"
- [x] Move Cancel button to link at bottom of form
- [x] Remove or hide Save button
- [x] Remove Import button (move to home page)
- [x] Make profile section expanded by default
- [x] "*Required Fields" labels

<img width="626" alt="screen shot 2018-10-01 at 11 48 38 am" src="https://user-images.githubusercontent.com/3093850/46309001-f529d000-c56f-11e8-9d2a-00d959af9bdf.png">

**Comment by ndushay** [comment]
@jgreben how much of this is done?  Just curious - no pressure.

**Comment by jgreben** [comment]
@ndushay this is all done.

**Comment by michelleif** [comment]
Description is marked as required with asterisk, but I'm able to create a new profile, leave the description field blank, and successfully export the profile with no warning/error message.

**Comment by jgreben** [comment]
Fixed by #103
