### ISSUE TITLE
home page integration tests

### ISSUE THREAD

**Issue by ndushay** [LD4P/sinopia_profile_editor#53]
Before redesign (tests that willl work after) - things that won't change
- test for scripts loading:   has link with href datepicker, etc.
- test for "new profile / create new profile" button - link with href `#/profile/create`

After redesign: we want to test for our changes, but we should have tests written for those as we go.

**Comment by jgreben** [comment]
We decided we don't need to test for links on home page because it does not include a script link to the app's javascript. Instead, we look for the `ng-app` attribute which names the angular application.

**Comment by jgreben** [comment]
Fixed by #55
