### ISSUE TITLE
tests for create profile page

### ISSUE THREAD

**Issue by ndushay** [LD4P/sinopia_profile_editor#54]
Before redesign (tests that willl work after) - things that won't change
- add resource template button/link:  exists and id="addResource" with ng-click="addResource()"
- Profile shows as h3 with word profile (heading for person's loaded profile(s))
- Profile accordian span with id=profileBanner and has 6 input fields 
- stuff about each input field?  is it worth it, eg. date input field is a datepicker, title input field is text
- cancel button with text cancel
- button/link with class fa-download ? (currently in i tag but will it stay there) -- whatever the magic is that makes it DO something 

After redesign: we want to test for our changes, but we should have tests written for those as we go, e.g.
- profile banner expanded

**Comment by jgreben** [comment]
Fixed by #68
