### ISSUE TITLE
Add global comments for eslint no-undef warnings

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_profile_editor#58]
When running eslint on the code-base we are receiving 200+ warnings about properties not being defined. Following the directions at https://eslint.org/docs/rules/no-undef, add `/* global angular */` (if the warning is about angular not defined) or other missing declarations in the code base.

**Comment by jgreben** [comment]
IMO it would be better to either research how to correct the code so that these warnings are fixed, or add to `.eslintrc.js`:
```
"globals": {
          "page": true,
          "angular": true
      }
```
See: https://eslint.org/docs/user-guide/configuring#specifying-globals

**Comment by jermnelson** [comment]
You're right, for **angular** and **page** `no-undef` warnings (maybe add those globals that are causing warnings in multiple files) ,  should be added to a globals section in the `.eslintrc.js` at least for now.

 For page specific `no-undef` warning, the global comment for those variables could be added to those pages.
