### ISSUE TITLE
CI pushes docker image to dockerhub

### ISSUE THREAD

**Issue by ndushay** [LD4P/sinopia_profile_editor#60]
upon successful tests passing, we want CI to push an image to docker hub.   That is, we only want to push the image to docker hub if it's master branch and if the tests pass.  (Should this depend on using our own docker container in circleci?  That's #22)

I think this is best handled with circleci workflows https://circleci.com/docs/2.0/workflows/

On pushing to and pulling from dockerhub:
https://ropenscilabs.github.io/r-docker-tutorial/04-Dockerhub.html

I think we have some examples here:
- https://github.com/sul-dlss-labs/rialto-derivatives/blob/master/.circleci/config.yml
- https://github.com/sul-dlss-labs/rialto-trigger-rebuild/blob/master/.circleci/config.yml
- https://github.com/sul-dlss-labs/taco/blob/master/.circleci/config.yml

**Comment by ndushay** [comment]
Note that I got as far as PR #74, but am now dropping this to work instead on breaking up bfe.js in ld4p/sinopia_editor.

**Comment by rsmith11** [comment]
Here's a quick pass at what I think might a circleci deploy to aws look like.  I basically merged both the taco and the rialto ones.  I don't have the circleci AWS keys yet, but I'd guess either Jon on Aaron would have them.

```
deploy_to_aws_dev:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/ld4p/sinopia_profile_editor
    steps:
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get install -y python-pip libyaml-dev python-dev jq
            sudo pip install awscli
      - checkout
      - run:
          name: Register Task & Update Service (dev)
          command: |
            mkdir ~/.aws
            echo -e "[sinopia]\naws_access_key_id=$CIRCLE_ACCESS_KEY_ID\naws_secret_access_key=$CIRCLE_SECRET_KEY\n" > ~/.aws/credentials
            unset  AWS_SESSION_TOKEN
            temp_role=$(aws sts assume-role \
                  --role-session-name "DevelopersRole" \
                  --role-arn $DEV_ROLE_ARN \
                  --profile sinopia)
            export AWS_ACCESS_KEY_ID=$(echo $temp_role | jq .Credentials.AccessKeyId | xargs)
            export AWS_SECRET_ACCESS_KEY=$(echo $temp_role | jq .Credentials.SecretAccessKey | xargs)
            export AWS_SESSION_TOKEN=$(echo $temp_role | jq .Credentials.SessionToken | xargs)
            aws configure set region $AWS_REGION
            aws configure set default.output json
            aws configure list  # Get confirmation it worked in your logs
            task_arn=$(aws ecs list-task-definitions --family-prefix sinopia-pe --sort DESC --max-items 1 | jq --raw-output --exit-status '.taskDefinitionArns[]')
            cluster_arn=$(aws ecs list-clusters --region $AWS_REGION | jq --raw-output --exit-status '.clusterArns[] | select(contains("sinopia"))')
            aws ecs update-service --cluster "$cluster_arn" --service sinopia-pe --task-definition "$task_arn" --region $AWS_REGION
```

**Comment by ndushay** [comment]
cool - thanks!
