### ISSUE TITLE
terraform automatically deploys new pushes to dockerhub

### ISSUE THREAD

**Issue by ndushay** [LD4P/sinopia_profile_editor#62]
for dev or stage environments (prod makes ops be on call)

depends on #61

**Comment by ndushay** [comment]
Here's something on deploying to AWS ECR/ECS if that's relevant.
https://circleci.com/docs/2.0/ecs-ecr/#section=deployment

**Comment by ndushay** [comment]
@atz  @jermnelson I think this is another duplicate or done ticket that might be closed?

**Comment by jermnelson** [comment]
Closed by #123
