### ISSUE TITLE
Choose Vocab Template Modal

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_profile_editor#93]
On a **Resource Template** or **Property Template**  title bar, clicking on the "hamburger" icon shows the Chose Vocab Template modal. 

This model is populated from verso calls and has a drop-down list that  has four vocabularies: 'LC BIBFRAME 2.0 Extensions', 'MADSRDF', 'Bibframe', and 'Languages'. Selecting a vocab, populates the list underneath that when the user clicks on, populates the template. These vocabularies are configured in [03-load-vocabs.js](https://github.com/lcnetdev/verso/blob/master/server/boot/03-load-vocabs.js) which loads the RDF OWL files for these vocabularies. 

A simple fix would be just to remove the hamburger icon link from the templates or to keep this functionality will require moving it into the sinopia_profile_editor code base.

**Comment by ndushay** [comment]
Notes:  branch ontologies-spoof should fix the modal to have title "Choose Vocab Template", with the appropriate test.  That branch will be a PR after #113 is merged.

I *think* this may actually be from `verso/server/boot/05-load-ontologies` unless there are two things with the same "vocab template" title.

**Comment by ndushay** [comment]
Looking at http://bibframe.org/profile-edit, it seems the hamburger icons for "Change Resource" and for "Change Property" and even for "Select Data Type" within property, by "Value Data Type" URI field all list:
- RDFS
- RDF
- MADS
- BFLC
- Bibframe 2.0

and that is what ours is showing as well (albeit in a different order).  

Am I looking in the wrong place?  Is the paragraph typed above listing the wrong things?  Is there something else I'm missing?

(Granted, these weren't populated before versoSpoof dealt with ontologies)

**Comment by ndushay** [comment]
I see those four values in `03-load-vocabs.js` but I don't know where to find them in the UI.

**Comment by jermnelson** [comment]
Closing this issue as it is fixed in PR#128.
