### ISSUE TITLE
Test that a template refers to a newly created "inner" template

### ISSUE THREAD

**Issue by jgreben** [LD4P/sinopia_profile_editor#99]
- [ ] Import a small template (e.g. “Place”) as an "inner" template
  - [ ] Test that expected form labels and fields exist
  - [ ] Change ID
  - [ ] Export the template
  - [ ] Test that json has values expected from template form
- [ ] Open an existing "outer" template (a template that will call the previously created Place template)
  - [ ] Add a new template (templateRef)
  - [ ] Check if the “new” Place template is in the dropdown
  - [ ] Select new Place template
- [ ] Export the template
- [ ] Check if `valueTemplateRef` has the new Place template ref in the exported json

**Comment by jgreben** [comment]
@jermnelson @ndushay note that the test specs as written will require that we have the ability to export and then immediately apply a templateRef. This may inform our plans for mocking/hacking the verso piece (github vs local files) or may require that we change the nature of the stated tests.

**Comment by michelleif** [comment]
We don't need this test since it's possible that a user will upload a template that refers to another template that hasn't been uploaded yet, and this is acceptable.
